hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("cando", views.cando, name="cando"),
    path("zataar", views.zataar, name="zataar"),
    path("<str:name>", views.greet, name="greet")
]

lecture3/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name="lecture3"
urlpatterns = [
    path('', views.index, name="index"),
    path('admin/', admin.site.urls),
    path('hello/', include('hello.urls')),
    path('newyear/', include('newyear.urls')),
    path('tasks/', include('tasks.urls'))
]

newyear/urls.py
from django.urls import path
import datetime
from . import views

urlpatterns = [
    path('', views.index, name="index")
]

tasks/urls.py
from django.urls import path
from . import views


app_name="tasks"
urlpatterns = [
    path('', views.index, name='index'),
    path('addtask', views.addtask, name='addtask')
]

newyear/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.db import models

# Create your models here.

hello/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request):
    return render(request, "hello/index.html")

def zataar(request):
    return HttpResponse("Hello Zataar")

def cando(request):
    return HttpResponse("Hello Cando!")

def greet(request, name):
    return render(request, "hello/greet.html", {
        "name": name
    })

lecture3/views.py
from django.shortcuts import render
# Create your views here.
def index(request):
    return render(request, 'lecture3/index.html')

newyear/views.py
from django.shortcuts import render
import datetime
# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, 'newyear/index.html', {
        "newyear": now.month == 12 and now.day == 2
    })

tasks/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect 
from django.urls import reverse

class NewTaskForm(forms.Form):
    task = forms.CharField(label = "New Task")
    priority = forms.IntegerField(label = "Priority", min_value=1, max_value=10)
    
tasks = ['Study Django', 'Study Docker', 'Study Kubernetes']

def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []
    return render(request, "tasks/index.html", {
        "tasks": request.session['tasks']
    }) 
    
def addtask(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data["task"]
            request.session["tasks"] += [data]
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request, "tasks/addtask.html",{
                    "form": form
            })
            
    return render(request, "tasks/addtask.html", {
        "form": NewTaskForm()
    })

hello/templates/hello/greet.html
<!DOCTYPE html>
<html>
<body>

<h1>My First Heading</h1>

<p>My first paragraph.</p>

</body>
</html>

hello/templates/hello/index.html
<!DOCTYPE html>
<html>
<body>

<h1>My First Heading</h1>

<p>My first paragraph.</p>

</body>
</html>

lecture3/templates/lecture3/index.html
{% load static %}

<!DOCTYPE html>
<html>
    <link href="{% static 'newyear/styles.css' %}" rel="stylesheet">
    <body>
       <h1> Welcome </h1>

       <a href="{% url 'tasks:index' %} "> View Tasks</a>
       <a href="{% url 'tasks:addtask' %}"> Add a task</a>
    </body>
</html>

newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html>
    <link href="{% static 'newyear/styles.css' %}" rel="stylesheet">
    <body>
        {% if newyear %}
           <h1>YES</h1>
        {% else %}
            <h1>NO</h1>
        {% endif %} 

   
    </body>
</html>

tasks/templates/tasks/addtask.html
{% load static %}
<!DOCTYPE html>
        <html lang="en">
            <head>
                
                <link rel="stylesheet" href="{% static 'tasks/styles.css' %}">
                <script src="main.js"></script>
                <title>Document</title>
            </head>
            <body>
                <h1> Add a Task </h1>
                <form action=' {% url "tasks:addtask" %}' method='post'> 
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit">
                </form>
                
                <a href=' {% url "tasks:index" %}'> View tasks </a>
  
            
            </body>
        </html> 

tasks/templates/tasks/index.html
{% load static %}
<!DOCTYPE html>
        <html lang="en">
            <head>
                
                <link rel="stylesheet" href="{% static 'tasks/styles.css' %}">
                <script src="main.js"></script>
                <title>Document</title>
            </head>
            <body>
                <ul> 
                    {% for task in tasks %}
                        <li> {{ task }} </li>
                    {% endfor %}

                </ul>
                
                <a href="{% url 'tasks:addtask' %}"> Add a task </a>
            
            </body>
        </html> 